### PR TITLE
Add CommonJS support

### PR DESCRIPTION
**Pull request by ntkoopman**
Makes it a little more intiuative to use with CommonJS supporting build tools (such as webpack).

The minified build will still need to be updated.

### CODE REVIEW

**Comment by steffenmllr** [comment]
Would be great if this could get merged

**Comment by jmas** [comment]
+

**Comment by sakren** [comment]
That would be really great.

But some people use amd instead of common js, so I think that it would be better to use something like [this](https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L4-L14).

**Comment by LPology** [comment]
@ntkoopman @steffenmllr @jmas @davidkudera This code change in SimpleAjaxUploader.js causes an undefined variable error to be thrown in the browser for `module`.

However, I just pushed an update that adds support for CommonJS.

Thanks to everyone for contributing. Sorry it took so long.

**Pull request closed without merging**
